name: Build
on:
  push:
    tags:
      - "v*"
    paths:
      - ".github/workflows/build.yml"
  workflow_dispatch:

jobs:
  build_win:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - uses: actions/cache@v3
        id: cache-node_modules
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build
        run: |
          yarn build:webpack
          yarn build:electron:win

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: electron-builder-win
          path: |
            build/SSH Log Viewer*.exe

  build_mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - uses: actions/cache@v3
        id: cache-node_modules
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build
        run: |
          yarn build:webpack
          yarn build:electron:mac

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: electron-builder-mac
          path: |
            build/SSH Log Viewer*.dmg

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn

      - uses: actions/cache@v3
        id: cache-node_modules
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build
        run: |
          yarn build:webpack
          yarn build:electron:linux

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: electron-builder-linux
          path: |
            build/SSH Log Viewer*.AppImage

  upload_release:
    runs-on: ubuntu-latest
    needs:
      - build_linux
      - build_mac
      - build_win
    steps:
      - name: Make directory
        run: mkdir -p release
      - name: Download windows package
        uses: actions/download-artifact@v3
        with:
          name: electron-builder-win
          path: |
            build/
      - name: Download mac package
        uses: actions/download-artifact@v3
        with:
          name: electron-builder-mac
          path: |
            build/
      - name: Download linux package
        uses: actions/download-artifact@v3
        with:
          name: electron-builder-linux
          path: |
            build/
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name || 'head' }}
          prerelease: ${{ !!github.ref_name }}
          tag_name: ${{ github.ref_name || 'head' }}
          files: build/*

